name: action-maven-publish
author: Samuel Meuli
description: GitHub Action for automatically publishing Maven packages

inputs:
  gpg_private_key:
    description: Base64-encoded GPG private key for signing the published artifacts
    required: true
  gpg_passphrase:
    description: Passphrase for the GPG key
    required: true
  nexus_username:
    description: Username (not email!) for your Nexus repository manager account
    required: true
  nexus_password:
    description: Password for your Nexus account
    required: true
  server_id:
    description: Nexus server ID as specified in your project's `nexus-staging-maven-plugin` and `distributionManagement` configurations
    required: false
    default: ossrh

runs:
  using: docker
  image: Dockerfile
  env:
    GPG_PRIVATE_KEY: ${{ inputs.gpg_private_key }}
    GPG_PASSPHRASE: ${{ inputs.gpg_passphrase }}
    NEXUS_USERNAME: ${{ inputs.nexus_username }}
    NEXUS_PASSWORD: ${{ inputs.nexus_password }}
    SERVER_ID: ${{ inputs.server_id }}

branding:
  icon: upload-cloud
  color: orange
